"""initial schema

Revision ID: 02e47f10f481
Revises: 
Create Date: 2026-01-19 17:01:10.687534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e47f10f481'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), server_default='none', nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('profilepic', sa.String(length=300), server_default='none', nullable=False),
    sa.Column('level', sa.String(length=2), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('learning_language', sa.String(length=10), nullable=False),
    sa.Column('delete_date', sa.Date(), nullable=True),
    sa.Column('user_stripe_id', sa.String(length=50), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('study_streak', sa.Integer(), nullable=True),
    sa.Column('max_study_streak', sa.Integer(), nullable=True),
    sa.Column('streak_last_date', sa.Date(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('max_points', sa.Integer(), nullable=True),
    sa.Column('flashcards_studied', sa.Integer(), nullable=True),
    sa.Column('rate_three_count', sa.Integer(), nullable=True),
    sa.Column('assigned_teacher_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['assigned_teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=True),
    sa.Column('end_hour', sa.Integer(), nullable=True),
    sa.Column('available_saturday', sa.Boolean(), nullable=True),
    sa.Column('available_sunday', sa.Boolean(), nullable=True),
    sa.Column('show_today', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('lesson_duration', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('identify_language', sa.Integer(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('ease', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=True),
    sa.Column('show_answer', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_tc', sa.Boolean(), nullable=False),
    sa.Column('add_by_tc', sa.Boolean(), nullable=False),
    sa.Column('add_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_audiobooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('text_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_audiobooks_user_id')
    )
    op.create_index(op.f('ix_user_audiobooks_user_id'), 'user_audiobooks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_audiobooks_user_id'), table_name='user_audiobooks')
    op.drop_table('user_audiobooks')
    op.drop_table('flashcards')
    op.drop_table('calendar_settings')
    op.drop_table('users')
    # ### end Alembic commands ###
