"""add audiobook library and chapter progress

Revision ID: 0ed410b6c1b8
Revises: 706e6cecfd2c
Create Date: 2026-08-03 21:53:17.598387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed410b6c1b8'
down_revision: Union[str, Sequence[str], None] = '706e6cecfd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('cover_object_name', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_slug'), 'books', ['slug'], unique=True)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('audio_object_name', sa.String(length=500), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'position', name='uq_chapters_book_position'),
    sa.UniqueConstraint('book_id', 'slug', name='uq_chapters_book_slug')
    )
    op.create_index(op.f('ix_chapters_book_id'), 'chapters', ['book_id'], unique=False)
    op.create_table('guest_chapter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_user_id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_user_id'], ['guest_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_user_id', 'chapter_id', name='uq_guest_chapter_progress')
    )
    op.create_index(op.f('ix_guest_chapter_progress_chapter_id'), 'guest_chapter_progress', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_guest_chapter_progress_guest_user_id'), 'guest_chapter_progress', ['guest_user_id'], unique=False)
    op.create_table('user_chapter_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chapter_id', name='uq_user_chapter_progress')
    )
    op.create_index(op.f('ix_user_chapter_progress_chapter_id'), 'user_chapter_progress', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_user_chapter_progress_user_id'), 'user_chapter_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_chapter_progress_user_id'), table_name='user_chapter_progress')
    op.drop_index(op.f('ix_user_chapter_progress_chapter_id'), table_name='user_chapter_progress')
    op.drop_table('user_chapter_progress')
    op.drop_index(op.f('ix_guest_chapter_progress_guest_user_id'), table_name='guest_chapter_progress')
    op.drop_index(op.f('ix_guest_chapter_progress_chapter_id'), table_name='guest_chapter_progress')
    op.drop_table('guest_chapter_progress')
    op.drop_index(op.f('ix_chapters_book_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_books_slug'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
