"""add level and role to guest users

Revision ID: 2643380990e8
Revises: 0ed410b6c1b8
Create Date: 2026-08-07 12:53:02.130623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2643380990e8'
down_revision: Union[str, Sequence[str], None] = '0ed410b6c1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_users', sa.Column('level', sa.String(length=2), nullable=True))
    op.add_column(
    "guest_users",
    sa.Column(
        "role",
        sa.String(length=10),
        nullable=False,
        server_default="student",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_users', 'role')
    op.drop_column('guest_users', 'level')
    # ### end Alembic commands ###
