"""adds cpf_cnpj field to user model

Revision ID: 2a72f4902778
Revises: 7cc19ab428bc
Create Date: 2026-04-07 18:45:25.443142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a72f4902778'
down_revision: Union[str, Sequence[str], None] = '7cc19ab428bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf_cnpj', sa.String(length=18), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cpf_cnpj')
    # ### end Alembic commands ###
