"""add guest flashcards

Revision ID: 6778e1bbdae0
Revises: 5c24d8f64051
Create Date: 2026-08-02 15:07:53.005138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6778e1bbdae0'
down_revision: Union[str, Sequence[str], None] = '5c24d8f64051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_user_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('ease', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_answer', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_tc', sa.Boolean(), nullable=False),
    sa.Column('add_by_tc', sa.Boolean(), nullable=False),
    sa.Column('add_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guest_user_id'], ['guest_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_flashcards_guest_user_id'), 'guest_flashcards', ['guest_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_flashcards_guest_user_id'), table_name='guest_flashcards')
    op.drop_table('guest_flashcards')
    # ### end Alembic commands ###
