"""add guest study statistics

Revision ID: 706e6cecfd2c
Revises: 6778e1bbdae0
Create Date: 2026-08-03 12:58:37.311595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706e6cecfd2c'
down_revision: Union[str, Sequence[str], None] = '6778e1bbdae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_users', sa.Column('study_streak', sa.Integer(), nullable=True))
    op.add_column('guest_users', sa.Column('max_study_streak', sa.Integer(), nullable=True))
    op.add_column('guest_users', sa.Column('streak_last_date', sa.Date(), nullable=True))
    op.add_column('guest_users', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('guest_users', sa.Column('max_points', sa.Integer(), nullable=True))
    op.add_column('guest_users', sa.Column('flashcards_studied', sa.Integer(), nullable=True))
    op.add_column('guest_users', sa.Column('rate_three_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_users', 'rate_three_count')
    op.drop_column('guest_users', 'flashcards_studied')
    op.drop_column('guest_users', 'max_points')
    op.drop_column('guest_users', 'points')
    op.drop_column('guest_users', 'streak_last_date')
    op.drop_column('guest_users', 'max_study_streak')
    op.drop_column('guest_users', 'study_streak')
    # ### end Alembic commands ###
