"""add asaas_customer_id to users

Revision ID: 7cc19ab428bc
Revises: be0f84faf921
Create Date: 2026-04-01 20:53:57.005177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc19ab428bc'
down_revision: Union[str, Sequence[str], None] = 'be0f84faf921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('asaas_customer_id', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'asaas_customer_id')
    # ### end Alembic commands ###
