"""set null guest claim on user delete

Revision ID: 943bfd36b0c2
Revises: 8c5c89896310
Create Date: 2026-08-17 20:17:05.163121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943bfd36b0c2'
down_revision: Union[str, Sequence[str], None] = '8c5c89896310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('guest_users_claimed_by_user_id_fkey'), 'guest_users', type_='foreignkey')
    op.create_foreign_key(None, 'guest_users', 'users', ['claimed_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guest_users', type_='foreignkey')
    op.create_foreign_key(op.f('guest_users_claimed_by_user_id_fkey'), 'guest_users', 'users', ['claimed_by_user_id'], ['id'])
    # ### end Alembic commands ###
