"""add billing_mode to users

Revision ID: be0f84faf921
Revises: 2cbde5ec05be
Create Date: 2026-03-23 23:58:42.399665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0f84faf921'
down_revision: Union[str, Sequence[str], None] = '2cbde5ec05be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('billing_mode', sa.String(length=20), nullable=True))
    op.execute("UPDATE users SET billing_mode = 'external'")
    op.alter_column('users', 'billing_mode', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'billing_mode')
    # ### end Alembic commands ###
