"""add pix_expires_at to payment

Revision ID: c1b57a31dbd8
Revises: 448c76bb9ffa
Create Date: 2026-04-09 12:42:56.276840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b57a31dbd8'
down_revision: Union[str, Sequence[str], None] = '448c76bb9ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('pix_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'pix_expires_at')
    # ### end Alembic commands ###
